### ISSUE TITLE
StParser cannot parse all methods

### ISSUE THREAD

**Issue by vonbecmann** [ThierryGoubier/SmaCC#11]
Pharo5.0
Latest update: #50760
StParser cannot parse all methods in the image. it has no tests.

| methods |
methods := OrderedCollection new.
Smalltalk globals allClassesDo: [ :class |
	class methods do: [ :method |
			[StParser parseMethod: method sourceCode.		]
				on: Error do: [ methods add: method ]
		 ]
	 ].
methods

**Comment by ThierryGoubier** [comment]
Corrected by 78442de
Except for one method which is outside StParser: the method cannot be recompiled in Pharo 6: the compiler fails with the same error as StParser, since they both use the same code to parse a number.
