### ISSUE TITLE
loadDevelopment throws a MNU

### ISSUE THREAD

**Issue by kilon** [ThierryGoubier/SmaCC#2]
if I follow the instructions of the front page and try to loadDevelopment in Pharo 4  ( release 40438) I get this MNU

[ (MetacelloSymbolicVersionDoesNotExistError project: self project versionString: aVersionString) signal ] in MetacelloMCProject(MetacelloProject)>>version: in Block: [ (MetacelloSymbolicVersionDoesNotExistError proje...etc...
Dictionary>>at:ifAbsent:
MetacelloMCProject(MetacelloProject)>>version:
[ :error | 
^ self version = 'last'
	ifTrue: [ 
		"manual fallback since there is no symbolic name for lastVersion"
		configuration lastVersion ]
	ifFalse: [ 
		"symbols and strings are not equal in Meteacello..."
		configuration version: self version asSymbol ] ] in GoferMetacelloLoad>>metacelloVersion in Block: [ :error | ...
BlockClosure>>cull:
Context>>evaluateSignal:
Context>>handleSignal:
MetacelloSymbolicVersionDoesNotExistError(Exception)>>signal
[ (MetacelloSymbolicVersionDoesNotExistError project: self project versionString: aVersionString) signal ] in MetacelloMCProject(MetacelloProject)>>version: in Block: [ (MetacelloSymbolicVersionDoesNotExistError proje...etc...
Dictionary>>at:ifAbsent:
MetacelloMCProject(MetacelloProject)>>version:
[ 
"First we try to load the latest version for a given version string"
^ (configuration latestVersion: self version)
	ifNil: [ 
		"If that doesn't work we use the default version lookup to find a version with the given name"
		configuration version: self version ] ] in GoferMetacelloLoad>>metacelloVersion in Block: [ ...
BlockClosure>>on:do:
GoferMetacelloLoad>>metacelloVersion
GoferMetacelloLoad>>loadConfiguration
GoferMetacelloLoad>>execute
Gofer>>execute:do:
Gofer>>loadVersion:
Gofer>>loadDevelopment
UndefinedObject>>DoIt
OpalCompiler>>evaluate
RubSmalltalkEditor>>evaluateSelectionAndDo:
[ textMorph textArea editor evaluateSelectionAndDo: ann action ] in GLMMorphicPharoPlaygroundRenderer(GLMMorphicPharoCodeRenderer)>>actOnEvaluateSelection: in Block: [ textMorph textArea editor evaluateSelectionAndDo...etc...
WorldState>>runStepMethodsIn:
WorldMorph>>runStepMethods
WorldState>>doOneCycleNowFor:
WorldState>>doOneCycleFor:
WorldState>>doOneSubCycleFor:
WorldMorph>>doOneSubCycle
MenuMorph>>invokeModalAt:in:allowKeyboard:

**Comment by ThierryGoubier** [comment]
I didn't test it on Pharo 4, only on Pharo 3.

Probably did domething as simple and silly than defining just a pharo3.x target :( Will solve it later tonight. Sorry for that.

**Comment by kilon** [comment]
no problemo take your time, no hurry :)

**Comment by ThierryGoubier** [comment]
I've updated the configuration so you should be able to load it in Pharo 4.

@kilon I'll go through all the tests now to make sure nothing is broken under 4.0. If you see anything suspicious, raise an additional issue. If you see configuration issues, then use this issue, I'll leave it open for now.

**Comment by kilon** [comment]
still does not load with the latest image of pharo 4 (just downloaded it) 

it gives this error

The symbolic version: #development is not defined in CofigurationOfSmaCC . Possible symbolic version values include:  #(#bleedingEdge #stable).



[ (MetacelloSymbolicVersionDoesNotExistError project: self project versionString: aVersionString) signal ] in MetacelloMCProject(MetacelloProject)>>version: in Block: [ (MetacelloSymbolicVersionDoesNotExistError proje...etc...
Dictionary>>at:ifAbsent:
MetacelloMCProject(MetacelloProject)>>version:
[ :error | 
^ self version = 'last'
	ifTrue: [ 
		"manual fallback since there is no symbolic name for lastVersion"
		configuration lastVersion ]
	ifFalse: [ 
		"symbols and strings are not equal in Meteacello..."
		configuration version: self version asSymbol ] ] in GoferMetacelloLoad>>metacelloVersion in Block: [ :error | ...
BlockClosure>>cull:
Context>>evaluateSignal:
Context>>handleSignal:
MetacelloSymbolicVersionDoesNotExistError(Exception)>>signal
[ (MetacelloSymbolicVersionDoesNotExistError project: self project versionString: aVersionString) signal ] in MetacelloMCProject(MetacelloProject)>>version: in Block: [ (MetacelloSymbolicVersionDoesNotExistError proje...etc...
Dictionary>>at:ifAbsent:
MetacelloMCProject(MetacelloProject)>>version:
[ 
"First we try to load the latest version for a given version string"
^ (configuration latestVersion: self version)
	ifNil: [ 
		"If that doesn't work we use the default version lookup to find a version with the given name"
		configuration version: self version ] ] in GoferMetacelloLoad>>metacelloVersion in Block: [ ...
BlockClosure>>on:do:
GoferMetacelloLoad>>metacelloVersion
GoferMetacelloLoad>>loadConfiguration
GoferMetacelloLoad>>execute
Gofer>>execute:do:
Gofer>>loadVersion:
Gofer>>loadDevelopment
UndefinedObject>>DoIt
OpalCompiler>>evaluate
RubSmalltalkEditor>>evaluateSelectionAndDo:
[ textMorph textArea editor evaluateSelectionAndDo: ann action ] in GLMMorphicPharoPlaygroundRenderer(GLMMorphicPharoCodeRenderer)>>actOnEvaluateSelection: in Block: [ textMorph textArea editor evaluateSelectionAndDo...etc...
WorldState>>runStepMethodsIn:
WorldMorph>>runStepMethods
WorldState>>doOneCycleNowFor:
WorldState>>doOneCycleFor:
WorldState>>doOneSubCycleFor:
WorldMorph>>doOneSubCycle
MenuMorph>>invokeModalAt:in:allowKeyboard:

**Comment by ThierryGoubier** [comment]
Hi @kilon , sorry for the delay.

I'll fix the configuration today and update the Smalltalkhub SmaCC repository; the configurations in the meta repository for Pharo 3 and 4 should work for the development version.

However, Pharo 4 has a bug which will prevent you to generate new parsers with SmaCC: https://pharo.fogbugz.com/default.asp?14729. You'll have to drop to Pharo 3, regenerate the parser in 3.0, and reload in 4.0.

**Comment by ThierryGoubier** [comment]
Ok, updated. Version of the configuration should be .31. The Pharo 4.0 bug is under resolution.

**Comment by kilon** [comment]
I will wait till Smacc is ready for Pharo 4, having a library that is ready to be used with latest Pharo is very important for me. None the less I will take a look at it and see what I can steal and maybe port to petitparser which I have to confess looks more elegant to me.

**Comment by ThierryGoubier** [comment]
Pharo 4.0 support should happen soon. The fix is ready for integration.

I'd say that the theory behind SmaCC is a lot stronger and elegant than in PetitParser, but harder to get into. But, when you start to get seriously into parsing, even with PetitParser, you'd better have a good grasp of that theory, and, at that level, SmaCC is just better. There is also a speed difference between the two.

**Comment by kilon** [comment]
Thats great, I will use whatever makes my lifer easier of course. I am very new with parsing , my goal is to parse python types like for example a string representation like '[1,40,50, [12,19,0],0]' which is a list that contains a list to pharo objects and some very basic parsing of pharo classes to python classes. So my demands are quite low right now and I dont care about full language parsing since I dont need such a feature for my project but of course it would not bad to have. I will have to download Pharo 3 and give Smacc a serious try. If I have question where you want me to ask them ? Is there a community that can help me understand Smacc ?

**Comment by ThierryGoubier** [comment]
As things stand, you can try the python parser in Pharo 4.0. I'll have a look if I can parse your examples, and maybe regenerate a parser.

**Comment by ThierryGoubier** [comment]
Here is what I have for your test sequence. I've pushed a new version so that you can just do:

PythonParser2 eval: '[1,40,50, [12,19,0],0]'

![capture du 2015-01-20 22 44 04](https://cloud.githubusercontent.com/assets/4500310/5826678/dd0f2e32-a0f4-11e4-8c9f-940b2bc5e741.png)
![capture du 2015-01-20 22 44 04](https://cloud.githubusercontent.com/assets/4500310/5826679/e19185a4-a0f4-11e4-89c4-5a945a148527.png)

**Comment by kilon** [comment]
OK it looks that install fine, I did not expect it to require so many pharo libraries. 

I tried your example but I don't get the browser you have in the screenshot and even if inspect I dont see anywhere an order collection with the numbers. I am reading the documentation at Smacc website to figure how this work. I also see that in your python parser tests you parse some really complex python code. Looks very promising. 

I really want to learn this, but I guess will take me some time to figure this out. It looks like it follow regular expression syntax which I am already familiar with because I have used already pharo regex library to parse pharo code to python code , mainly simple stuff like python calls and variable assignments.

**Comment by plantec** [comment]
Hello Thierry,
cool.
I guess the parser comme from the one I wrote with an older version of smacc.
I will have a look.
this node browser is packaged with the python parser or is it a generic one ?
thanks
Alain

**Comment by ThierryGoubier** [comment]
Hi Alain @plantec, yes, I had a look on the old one (I remember @DamienCassou coming up with questions on running the old one on SmaCC v2) and I decided to rewrite it: the indent / dedent / line handling was too tied to the scanner implementation of SmaCC v1, and I believe the scanner is now a bit simpler. I also wanted to use the SmaCC v2 ast generation approach, so I restarted from the Python 2.7 official grammar.

The node browser is in a package named SmaCC-Browser, and it requires Al-TreeMorph from Alt-Browser (and I don't think I have the requirements set-up correctly yet... still experimental). It browses any AST from any SmaCC parser with the ast generation code.

@kilon , the python tests come from the old python parser, and, yes, they are fairly complete. First level of the parser are token classes; and those are RE as you noticed. They are compiled in PythonScanner2 in the scanXX methods, if you want to have a look. The remainder of the grammar is LALR.

**Comment by plantec** [comment]
> Le 21 janv. 2015 à 09:19, Thierry Goubier <notifications@github.com> a écrit :
> 
> Hi Alain @plantec <https://github.com/plantec>, yes, I had a look on the old one (I remember @DamienCassou <https://github.com/DamienCassou> coming up with questions on running the old one on SmaCC v2) and I decided to rewrite it: the indent / dedent / line handling was too tied to the scanner implementation of SmaCC v1, and I believe the scanner is now a bit simpler. I also wanted to use the SmaCC v2 ast generation approach, so I restarted from the Python 2.7 official grammar.
> 
> 

super! 
> The node browser is in a package named SmaCC-Browser, and it requires Al-TreeMorph from Alt-Browser (and I don't think I have the requirements set-up correctly yet... still experimental). It browses any AST from any SmaCC parser with the ast generation code.
> 
> 

I will make a try

thanks

Alain

**Comment by kilon** [comment]
just a side not, loading SmaCC on Ubuntu fails because it needs SSH keys. So this install will fail for anyone that has not setup git and not familiar with github. I think it uses the ssh address hence why it fails without a ssh key, maybe if it used https instead would not have this problem but I dont know if is a SmaCC issues a gitfiletree issue or a filetree issue. 

 Thanks for the pointers I am looking at the code and try to understand it, will be back with any questions. Do you want me to ask here ? in pharo-user mailing list ? Stackoverflow ?

**Comment by ThierryGoubier** [comment]
@kilon , Yes, it should fail with the ssh key issue, but the github for SmaCC is mostly for development. I'll update the instructions for the stable version.

For questions, I don't have a StackOverflow account, so I won't see them. Pharo-users is a good idea, some questions may be of interest to the PetitParser users as well.

**Comment by kilon** [comment]
Great I will ask in the Pharo-user mailing list then, as always thank you for helping me out :)
