### ISSUE TITLE
Syntax error causes MNU

### ISSUE THREAD

**Issue by apblack** [ThierryGoubier/SmaCC#38]
I have a grammar that starts as follows:
```
%unicode ;
<name> :  [a-zA-Z]  ([a-zA-Z]  | [0-9] | _ | ')*;
<h> : [0-9a-fA-F] ;
%states string uninterpString;
string <stringSegment>: ( \\[nt\{\}\"rl_] | \\u<h><h><h><h> | \\U<h><h><h><h><h><h> | \xA0 | [^\"\{\\] )+ ;
uninterpString <uninterpretedStringChar>: [^›] ;
<decimalNumeral> :  [0-9]+ ( [.][0-9]+ )? ;
<baseExponentNumeral> : <decimalNumeral> [eE][\+\-]?[0-9]+ ;
<basedRadixNumeral>: [0-9]+x[0-9A-Za-z]+ ;
<whitespace>:  (\x20|\xA0|\r)* ;
<arrow>:  ->  ;
<dquote>:  ["];
<dot>: \.;
<elipsis>: \.\.\.;
<operator>: [!\?@#%^&\|~=\+\-\*/\\><:\.$]+  # or any unicode mathematical operator symbol

%prefix Grace ;
%suffix Node ;
%root Root ;
%annotate_tokens ;
%start Block Expression Numeral Request String;

Program
	: ExpressionList
	;
Block
	# this is written as two alternatives, rather than making ParameterList optional,
	# because the latter creates a shift-reduce conflict that SmaCC can't resolve.
	: "{" (ParameterList  'parameters' <arrow> ) ExpressionList  'body' ? "}"  {{}}
	| "{" ExpressionList 'body' ? "}"  {{}}
	;
```

Notice that there is an error in this input: there needs to be a semicolon after the definition of `<operator>`.   If I compile the definition as written, instead of a syntax error message, a message is sent to `nil` and I get a walkback.

The error occurs in method SmaCCRedueActionGenerator >># connectChild, which starts
```
connectChild
	| variableDefinition argument symbol isCollection |
	variableDefinition := rhs nodeType
		variableDefinitionNamed: variableName.
```
`rhs nodeType` can return `nil`; this is not handled by the above code.

This walkback seems to occur when parsing the second grammar production _after_ the above error, i.e., `rhs` is `"{" ExpressionList ? "}"`.

**Comment by ThierryGoubier** [comment]
The error is linked to the lack of effective `%prefix Grace;` 

The missing `;` at the end of \<operator\> does a regular expression which includes the next line up to the first `;`, so eating the line `%prefix Grace;` inside \<operator\>.

I'm tempted to fix that by making `<cr>` and comments `#` not allowed as part of a regular expression. And halting the ast generation if I don't have all three `%prefix, %root and %suffix`.

**Comment by ThierryGoubier** [comment]
Handled by a15fb86: % characters have to be escaped in regular expressions.

**Comment by apblack** [comment]
Producing an error (instead of trying to generate the AST nodes) if not att three of %prefix, %root and %suffix are present would seem like a good idea.

Thanks for the fix!

**Comment by ThierryGoubier** [comment]
I'll add a need to escape `$:` and `$<` as well, so that a missing `$;` at the end of a regular expression is caught as a syntax error as early as possible.

The difficulty is that the grammar parser is scanning in `#tryAllTokens` mode, so it easily allow the parser to fall back on another interpretation of a token and so make regular expressins very greedy.
