### ISSUE TITLE
Undeclared token does not raise an error 

### ISSUE THREAD

**Issue by apblack** [ThierryGoubier/SmaCC#41]
If I spell the name of a token incorrectly in the grammar, I don't get a compilation error.  I just get a grammar that doesn't work.
For example, if in a production I write `<nome>` instead of `<name>`, or `<Outer>` instead of `<outer>`, I don't get a compilation error (or even a warning message).  I just get a parser that doesn't do what I expect.

It's almost like programming in Python!

**Comment by ThierryGoubier** [comment]
This may break some grammars.

**Comment by apblack** [comment]
I think that I would claim that they were already broken!

**Comment by ThierryGoubier** [comment]
Good. I could not get all the tests green on my laptop... and they take forever to run. I'll check all the grammars I have.

**Comment by ThierryGoubier** [comment]
Ok, clear.
