### ISSUE TITLE
REs excluding control characters cause compilation problems

### ISSUE THREAD

**Issue by apblack** [ThierryGoubier/SmaCC#45]
In my grammar I have the following rule:

```
string <stringSegment> : ( \\[nt\{\}\"rl_] | \\u<h><h><h><h> | \\U<h><h><h><h><h><h> | \xA0 | [^\"\{\\\x00-\x09] ) + ;
```

This is saying that a string segment may not contain an un-escapsed `"`, `{`, `\`, or any of the control characters between `0` and `x09`.

This works, but it's not quite right.  I also want to exclude `x0b`, `x0c`, `x0e`-`x1f` and `x7f`.. But if I add `\x0b` after the `\x09`, SmaCC seems to go into an infinite loop while evaluating estimatedSize on the character set. 

I have `%unicode` set, so the loop may not be actually infinite, but a power of `SmaCCGrammar maximumCharacterValue`.  It's effectively the same thing.

**Comment by apblack** [comment]
The problem seems to be using a lower-case `b` as a hex digit in the `\x` encoding.  `\x0B` and `\x0C` works fine!  A similar problem occurs with the `\c` encodings.  But adding the range `\x0E–\x1F` kills it.

**Comment by ThierryGoubier** [comment]
With the `%unicode;` option, I could compile without long wait times the following:

`<string> : \' (\xA0 | [^\"\{\\\x00-\x09\x0b\x0c\x0e-\x1f] ) + \' ;`

So I consider this issue solved.
