### ISSUE TITLE
Using predicates in REs causes problems

### ISSUE THREAD

**Issue by apblack** [ThierryGoubier/SmaCC#46]
This may be the same issue as #45, but it manifests a bit differently.

I had a definition

    <name> : [A-Za-z_] [A-Za-z0-9_'] * ;

which worked fine until I tried a test on a name that contains the character æ.  (æ is a Latin1 character classified as a lower-case letter, at codePoint 230 = U+00E6).  So I changed my RE to

    <name> :  ( <isLetter> | _ ) |  ( <isLetter> | <isDigit> | _ | ' ) * ;

Compiling the grammar now seems not to terminate.  When I interrupt the compilation, the top few stack frames look the same as in issue #45:

![screen shot 2017-10-12 at 18 09 58](https://user-images.githubusercontent.com/410893/31506764-b46cc09e-af78-11e7-8a36-00b3a339adef.png)

**Comment by ThierryGoubier** [comment]
@apblack ,

in the latest SmaCC, there is no issue with the <isLetter> pattern (it correctly includes æ if you add the %unicode directive); compilation of the parser should be reasonably fast (the set of <isLetter> should be properly cached).

However, your pattern is wrong:

`<name> :  ( <isLetter> | _ ) |  ( <isLetter> | <isDigit> | _ | ' ) * ;`

allow for <name> to be empty, so it creates issues in all parsers. A better pattern would be:

`<name> :  ( <isLetter> | _ ) ( <isLetter> | <isDigit> | _ | ' ) * ;`

(Just removing the | to ensure you have at least one letter or an _)
