### ISSUE TITLE
Scanner incorrectly classifies Unicode input 

### ISSUE THREAD

**Issue by apblack** [ThierryGoubier/SmaCC#53]
I just updated my copy of SmaCC to commit 2e7029d9bd6d8aaafb03df977b29661b5fea971d.  (I've been delaying until I fixed some parser issues of my own making.)  Now 9 of my parser tests fail, because the input symbol ⟧ (Character value: 10215), which should be a <closeTP>,  is being mis-classified.

The generated method `scan1X20` contains this code:
```
	currentCharacter =
		(Character value: 10215)
		ifTrue: [ ^ self recordAndReportMatch: #(52 53) ].
	(currentCharacter
		between: (Character value: 10214)
		and: (Character value: 10215))
		ifTrue: [ ^ self recordAndReportMatch: #(52) ].
```
Characters value 10214 and 10215 are ⟦ and ⟧, which I use as type parameter brackets; they are symbols 52 and 53.    The above code is weird, both because 10215 should be classified as _only_ Symbol 52, and because the second test is for a range that contains exactly two items, the first of which has just been excluded.

The parser consequently classifies the ⟧ as an <openTP> symbol, which breaks the parser.

If I change this by hand to:
```
	currentCharacter =
		(Character value: 10215)
		ifTrue: [ ^ self recordAndReportMatch: #(53) ].
	currentCharacter = 
		(Character value: 10214)
		ifTrue: [ ^ self recordAndReportMatch: #(52) ].
```
everything works as expected.

This looks like #47, but now there are no "isExpressions" involved.   I did try setting the array of available isExpressions to `#()` (in `reduceActionForUnicode1`); this merely moved the erroneous generated code from `scan1X20` to `scan1X22`

This issue is more-or-less a show-stopper for me.

**Comment by ThierryGoubier** [comment]
Hi @apblack ,

I changed the generation to allways respect unicode categories, if applicable; now, this may have triggered an issue (I can't even type those characters in Ubuntu ... how do you type them?) . I'll add a test and look into it.

**Comment by apblack** [comment]
I'm not sure why Unicode categories should affect this, but I agree that getting a failing test would be a good first step.

It seems to me that this issue might be intermittent, perhaps being dependent on the enumeration order of a set of characters.

I type ⟦ and ⟧ by holding down control + option and typing [ and ], but this works on OSX only because I added the appropriate customization to the text editing widget.   You can always cut and paste these characters from this issue report!

**Comment by apblack** [comment]
As an experiment, I defined methods `isOpenOxfordBracket` and `isCloseOxfordBracket` that answer `true` for `⟦` and `⟧`, and enabled these methods as `isExpressions`.  The generated code then contains the fragment:
```
	currentCharacter isCloseOxfordBracket
		ifTrue: [ ^ self recordAndReportMatch: #(52 53) ].
	(currentCharacter isCloseOxfordBracket
		or: [ currentCharacter isOpenOxfordBracket ])
		ifTrue: [ ^ self recordAndReportMatch: #(52) ].
```
It's effectively the same bug as above, but I found it interesting that this bug is robust across this alternate form.

**Comment by ThierryGoubier** [comment]
Interesting. I work with a test case where just the ordering between the two is changed, and the ⟧ is not mixed with the ⟦, but yes there is this strange

```smalltalk
	(currentCharacter == $]
		or: [ currentCharacter =
				(Character value: 10215) ])
		ifTrue: [ ^ self recordAndReportMatch: #(8) ].
	(currentCharacter == $[
		or: [ currentCharacter
				between: (Character value: 10214)
				and: (Character value: 10215) ])
		ifTrue: [ ^ self recordAndReportMatch: #(9) ].
```

**Comment by ThierryGoubier** [comment]
Stranger again: if you include only one of those characters in the grammar definition, then the range test isn't generated...

**Comment by ThierryGoubier** [comment]
Found something: it is triggered by the presence of keywords in the grammar. But not if there is no keywords...

Test cases added with b8ddd3a.

**Comment by ThierryGoubier** [comment]
Found it: false data sharing in `SmaCCIntegerSet>>#addAll:` implementation. Fix is a one liner, in e130c46.

**Comment by apblack** [comment]
Wow!  Isn't it amazing how a bug like that can lie dormant for so long.  I was thinking that this smelled like something wrong with Set ... but figured that you would find it before I had managed to look.

Thank you!

**Comment by ThierryGoubier** [comment]
This bug is only triggered if you have two integer sets that are holding large enough numbers, and if you add one of them to an integer set holding small numbers, and if you do that at least twice. So I'm not surprised it went hidden for a long time.

I was more surprised by the fact I needed a deepCopy to correct it; a copy would not solve it. But in restrospect, given the structure is a tree of byte arrays, I should have expected the need for a deep copy.
