### ISSUE TITLE
right-mouse click:MenuMorph DNU  labels: labelsString lines: linesArray selections: selections

### ISSUE THREAD

**Issue by StephanEggermont** [ThierryGoubier/SmaCC#6]
right mouse click in either of the text panes. 40524

See issue https://pharo.fogbugz.com/f/cases/13701

Since 40146

**Comment by ThierryGoubier** [comment]
Looks like I'll need to make a pharo4 branch soon ;)

Thanks for the report.

Thierry

2015-03-02 15:08 GMT+01:00 Stephan Eggermont <notifications@github.com>:

**Comment by ThierryGoubier** [comment]
closed by commit d0041068cbaa31df1b2373b582fdaaf9291a6255
