### ISSUE TITLE
SmaCC does not recognise Non Breaking Spaces as whitespaces (\s).

### ISSUE THREAD

**Issue by serpi90** [ThierryGoubier/SmaCC#9]
Non Breaking Spaces: (HTML: `&nbsp`; or ASCII 160) is not matched as whitespace when using \s.

**Comment by ThierryGoubier** [comment]
Hi @serpi90, I checked and, depending on the platform, the tool and the programming language, ASCII 160 is considered as whitespace or not (example: ruby allows ascii 160 in identifiers).

**Comment by serpi90** [comment]
Then i'll add it manually in my expression, thank you.

Considering it's non standard i'll close the issue.
